In [5]:
import copy
import numpy as np
import cv2
import matplotlib.pyplot as plt
def style_transfer(image, ref) :
    #out = np.zeros_like(ref)
    out = copy.deepcopy(image)
    hist_img, _ = np.histogram(image[ : , :  ], bins = 256)
    #生成直方图，第一个为要操作的数组，bins参数是指定统计的区间个数,代表不同的灰度级
    #返回值是hist和bins
    #print(hist_img)
    #print(_)
    hist_ref, _ = np.histogram(ref[ : , : ], 256)
    #print(hist_img.shape)
    cdf_img = np.cumsum(hist_img)#展平求前缀和
    cdf_ref = np.cumsum(hist_ref)
    
    for j in range(256) :
        tmp = abs(cdf_img[j] - cdf_ref)#找出在两个直方图中的映射点，即相差最小的对应灰度值
        tmp = tmp.tolist()#将其他形式的数据转化成列表
        idx = tmp.index(min(tmp))
        '''for i in range(out.shape[0]) :
            for k in range(out.shape[1]) :
                if image[i][k] == j :
                    out[i][k] = idx'''
        out[image[ : , : ] == j] = idx#表示在out数组中下标为image数组中灰度值为j的地方均用idx代替
    print(out)
    return out
img1 = cv2.imread('shenzhen_gray.bmp', cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread('dark-city.jpg', cv2.IMREAD_GRAYSCALE)
img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]))
img3 = style_transfer(img1, img2)
#plt.hist(img3)
#plt.show()

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('img3', img3)
cv2.waitKey(0)

[[214 214 214 ...   9   9   9]
 [214 214 220 ...   9   9  10]
 [200 209 209 ...  10   9  10]
 ...
 [  0   0   0 ...   0   0   1]
 [  0   0   0 ...   0   0   1]
 [  0   0   0 ...   0   0   0]]


-1