In [2]:
import numpy as np
import cv2 as cv
import copy

Image1 = cv.imread('data/shenzhen_gray.bmp', cv.IMREAD_GRAYSCALE)
# print(Image1.shape)
# gimage = cv.cvtColor(Image1, cv.COLOR_GRAY2BGR)
# print(gimage.shape)
cimage = copy.deepcopy(Image1).astype(np.float)
for i in range(cimage.shape[0]) :
    for j in range(cimage.shape[1]) :
        if cimage[i][j] < 90 :
            cimage[i][j] = 0.2 * cimage[i][j]
        elif 90 < cimage[i][j] < 160 :
            cimage[i][j] = 3 * cimage[i][j]
        else :
            cimage[i][j] = 0.8  * cimage[i][j]
cimage = cimage.astype(np.uint8)
cv.imshow('cimage', cimage)
cv.imshow('Image1', Image1)
cv.waitKey()

<ipython-input-2-ab9001349ddf>:9: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  cimage = copy.deepcopy(Image1).astype(np.float)


[[243. 243. 243. ...  96.  96.  98.]
 [243. 243. 244. ...  97.  98.  99.]
 [240. 242. 242. ...  99.  98. 100.]
 ...
 [  9.  10.  23. ...  41.  43.  54.]
 [  6.  10.  16. ...  37.  45.  53.]
 [  6.   9.  15. ...  32.  38.  45.]]


-1